language: generic
dist: xenial
sudo: false

addons:
  apt:
    packages:
      - vim

before_script:
  - git clone https://github.com/thinca/vim-themis --quiet --branch v1.5.4 --single-branch --depth 1 /tmp/vim-themis

script:
  - vim --version
  - /tmp/vim-themis/bin/themis --reporter dot

notifications:
  email: false
